# string manipulation suite
secret_code="p_y_t_h_o_n_i_s_a_w_e_s_m_e" 
code=(secret_code[0:11:2])
print(code)
user=input("what is your name?: ") 
print(user[0:4])
print(user[-1])
print(user[::-1])
print(user.upper())
print(len(user)) 
print(user.rstrip(user))
print(user.split(""))
print(user.capitalize())
print(user.center(50))
print(user.count("s"))
print(user.endswith("m"))
print(user.find("a")) # jodi vul take ta hole 1 return korbe
print(user.isalnum())
print(user.islower())
print(user.isspace())
print(user.isprintable())
print(user.istitle())
print(user.startswith("s"))
print(user.swapcase())
print(user.title())
